const trainsBtwStationResponse = {
  status: true,
  message: "Success",
  timestamp: 1719380774635,
  data: [
    {
      train_number: "12424",
      train_name: "Rajdhani Express",
      run_days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      train_src: "NDLS",
      train_dstn: "DBRG",
      from_std: "21:07",
      from_sta: "21:02",
      local_train_from_sta: 1262,
      to_sta: "19:25",
      to_std: "19:40",
      from_day: 0,
      to_day: 1,
      d_day: 0,
      from: "CNB",
      to: "GHY",
      from_station_name: "KANPUR CENTRAL",
      halt_stn: 13,
      distance: 1423,
      to_station_name: "GUWAHATI",
      duration: "22:18",
      special_train: false,
      train_type: "RAJ",
      score: 25,
      score_train_type: 5,
      score_booking_requency: 0,
      frequency_perc: 0,
      from_distance_text: "",
      to_distance_text: "",
      has_pantry: true,
      is_monsoon_timing_applicable: false,
      duration_rating: 1,
      score_duration: 10,
      score_std: 10,
      score_user_preferred: 0,
      train_date: "28-06-2024",
      class_type: ["3A", "2A", "1A"],
    },
    {
      train_number: "14038",
      train_name: "Poorvottar Sampark Kranti Express",
      run_days: ["Fri"],
      train_src: "NDLS",
      train_dstn: "SCL",
      from_std: "05:25",
      from_sta: "05:20",
      local_train_from_sta: 1760,
      to_sta: "07:40",
      to_std: "07:55",
      from_day: 1,
      to_day: 2,
      d_day: 1,
      from: "CNB",
      to: "GHY",
      from_station_name: "KANPUR CENTRAL",
      halt_stn: 8,
      distance: 1530,
      to_station_name: "GUWAHATI",
      duration: "26:15",
      special_train: false,
      train_type: "SKRT",
      score: 25,
      score_train_type: 5,
      score_booking_requency: 0,
      frequency_perc: 0,
      from_distance_text: "",
      to_distance_text: "",
      has_pantry: true,
      is_monsoon_timing_applicable: false,
      duration_rating: 2,
      score_duration: 10,
      score_std: 10,
      score_user_preferred: 0,
      train_date: "28-06-2024",
      class_type: ["SL", "3E", "3A", "2A", "1A"],
    },
    {
      train_number: "12506",
      train_name: "North East SF Express",
      run_days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      train_src: "ANVT",
      train_dstn: "KYQ",
      from_std: "13:35",
      from_sta: "13:25",
      local_train_from_sta: 805,
      to_sta: "16:25",
      to_std: "16:25",
      from_day: 0,
      to_day: 1,
      d_day: 0,
      from: "CNB",
      to: "KYQ",
      from_station_name: "KANPUR CENTRAL",
      halt_stn: 23,
      distance: 1417,
      to_station_name: "KAMAKHYA",
      duration: "26:50",
      special_train: false,
      train_type: "SUF",
      score: 21,
      score_train_type: 5,
      score_booking_requency: 0,
      frequency_perc: 0,
      from_distance_text: "",
      to_distance_text: "6 Kms from GHY",
      has_pantry: true,
      is_monsoon_timing_applicable: false,
      duration_rating: 2,
      score_duration: 6,
      score_std: 10,
      score_user_preferred: 0,
      train_date: "28-06-2024",
      class_type: ["SL", "3E", "3A", "2A", "1A"],
    },
    {
      train_number: "15657",
      train_name: "Brahmaputra Mail",
      run_days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      train_src: "DLI",
      train_dstn: "KYQ",
      from_std: "05:35",
      from_sta: "05:30",
      local_train_from_sta: 1770,
      to_sta: "13:20",
      to_std: "13:20",
      from_day: 1,
      to_day: 2,
      d_day: 1,
      from: "CNB",
      to: "KYQ",
      from_station_name: "KANPUR CENTRAL",
      halt_stn: 37,
      distance: 1593,
      to_station_name: "KAMAKHYA",
      duration: "31:45",
      special_train: false,
      train_type: "MEX",
      score: 21,
      score_train_type: 5,
      score_booking_requency: 0,
      frequency_perc: 0,
      from_distance_text: "",
      to_distance_text: "6 Kms from GHY",
      has_pantry: true,
      is_monsoon_timing_applicable: false,
      duration_rating: 4,
      score_duration: 6,
      score_std: 10,
      score_user_preferred: 0,
      train_date: "28-06-2024",
      class_type: ["SL", "3E", "3A", "2A", "1A"],
    },
    {
      train_number: "19305",
      train_name: "Dr Ambedkar Nagar - Kamakhya Express",
      run_days: ["Fri"],
      train_src: "DADN",
      train_dstn: "KYQ",
      from_std: "04:00",
      from_sta: "03:55",
      local_train_from_sta: 1675,
      to_sta: "12:30",
      to_std: "12:30",
      from_day: 1,
      to_day: 2,
      d_day: 1,
      from: "CNB",
      to: "KYQ",
      from_station_name: "KANPUR CENTRAL",
      halt_stn: 24,
      distance: 1550,
      to_station_name: "KAMAKHYA",
      duration: "32:30",
      special_train: false,
      train_type: "MEX",
      score: 19,
      score_train_type: 5,
      score_booking_requency: 0,
      frequency_perc: 0,
      from_distance_text: "",
      to_distance_text: "6 Kms from GHY",
      has_pantry: false,
      is_monsoon_timing_applicable: false,
      duration_rating: 4,
      score_duration: 4,
      score_std: 10,
      score_user_preferred: 0,
      train_date: "28-06-2024",
      class_type: ["SL", "3E", "3A", "2A"],
    },
  ],
};

export default trainsBtwStationResponse;
